version: '3.8'

services:
  # Backend API Service
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MODEL_PATH=/app/model/mango_model.h5
    volumes:
      - ./backend/model:/app/model
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped

  # Optional: PostgreSQL Database
  # database:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: mangodb
  #     POSTGRES_USER: mango_user
  #     POSTGRES_PASSWORD: mango_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # Optional: Redis Cache
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

  # Optional: Nginx Reverse Proxy
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - backend
  #     - frontend
  #   restart: unless-stopped

# Optional: Named volumes
volumes:
  postgres_data: